CREATE TABLE [dbo].[tblFumigationRouts] (
    [FumigationRoutsId] INT             IDENTITY (1, 1) NOT NULL,
    [RouteNo]           INT             NULL,
    [FumigationId]      INT             NULL,
    [FumigationTypeId]  INT             NULL,
    [AirWayBill]        VARCHAR (50)    NULL,
    [CustomerPO]        VARCHAR (50)    NULL,
    [ContainerNo]       VARCHAR (50)    NULL,
    [PickUpLocation]    INT             NULL,
    [PickUpArrival]     DATETIME        NULL,
    [FumigationSite]    INT             NULL,
    [FumigationArrival] DATETIME        NULL,
    [DeliveryLocation]  INT             NULL,
    [DeliveryArrival]   DATETIME        NULL,
    [PalletCount]       DECIMAL (18, 2) NULL,
    [BoxCount]          DECIMAL (18, 2) NULL,
    [BoxType]           INT             NULL,
    [Temperature]       DECIMAL (10, 2) NULL,
    [TemperatureType]   VARCHAR (5)     NULL,
    [Pricing]           VARCHAR (20)    NULL,
    [MinFee]            DECIMAL (18, 2) NULL,
    [AddFee]            DECIMAL (18, 2) NULL,
    [TrailerPosition]   DECIMAL (18, 2) NULL,
    [TotalFee]          DECIMAL (18, 2) NULL,
    [IsDeleted]         BIT             DEFAULT ((0)) NOT NULL,
    [DeletedOn]         DATETIME        NULL,
    [DeletedBy]         INT             NULL,
    PRIMARY KEY CLUSTERED ([FumigationRoutsId] ASC),
    FOREIGN KEY ([DeletedBy]) REFERENCES [dbo].[tblUser] ([Userid]),
    FOREIGN KEY ([FumigationId]) REFERENCES [dbo].[tblFumigation] ([FumigationId])
);

