
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LarastruckingApp.Repository.EF
{

using System;
    using System.Collections.Generic;
    
public partial class tblAddress
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblAddress()
    {

        this.tblBaseFreightDetails = new HashSet<tblBaseFreightDetail>();

        this.tblBaseFreightDetails1 = new HashSet<tblBaseFreightDetail>();

        this.tblBaseFreightDetails2 = new HashSet<tblBaseFreightDetail>();

        this.tblBaseFreightDetails3 = new HashSet<tblBaseFreightDetail>();

        this.tblCustomerBaseFreightDetails = new HashSet<tblCustomerBaseFreightDetail>();

        this.tblCustomerBaseFreightDetails1 = new HashSet<tblCustomerBaseFreightDetail>();

        this.tblCustomerBaseFreightDetails2 = new HashSet<tblCustomerBaseFreightDetail>();

        this.tblCustomerBaseFreightDetails3 = new HashSet<tblCustomerBaseFreightDetail>();

        this.tblQuoteRouteStops = new HashSet<tblQuoteRouteStop>();

        this.tblQuoteRouteStops1 = new HashSet<tblQuoteRouteStop>();

        this.tblQuoteRouteStops2 = new HashSet<tblQuoteRouteStop>();

        this.tblQuoteRouteStops3 = new HashSet<tblQuoteRouteStop>();

        this.tblTrailerRentalDetails = new HashSet<tblTrailerRentalDetail>();

        this.tblTrailerRentalDetails1 = new HashSet<tblTrailerRentalDetail>();

    }


    public int AddressId { get; set; }

    public int AddressTypeId { get; set; }

    public string CompanyName { get; set; }

    public string Address1 { get; set; }

    public string Address2 { get; set; }

    public string City { get; set; }

    public Nullable<int> State { get; set; }

    public string Zip { get; set; }

    public Nullable<int> Country { get; set; }

    public string ContactPerson { get; set; }

    public string Phone { get; set; }

    public string Extension { get; set; }

    public string AdditionalPhone1 { get; set; }

    public string Extension1 { get; set; }

    public string AdditionalPhone2 { get; set; }

    public string Extension2 { get; set; }

    public string Email { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<System.DateTime> ModifiedOn { get; set; }

    public Nullable<int> ModifiedBy { get; set; }

    public bool IsDeleted { get; set; }

    public bool IsActive { get; set; }

    public string Comments { get; set; }

    public bool IsAppointmentRequired { get; set; }

    public string Website { get; set; }

    public string CompanyNickname { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblBaseFreightDetail> tblBaseFreightDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblBaseFreightDetail> tblBaseFreightDetails1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblBaseFreightDetail> tblBaseFreightDetails2 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblBaseFreightDetail> tblBaseFreightDetails3 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblCustomerBaseFreightDetail> tblCustomerBaseFreightDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblCustomerBaseFreightDetail> tblCustomerBaseFreightDetails1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblCustomerBaseFreightDetail> tblCustomerBaseFreightDetails2 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblCustomerBaseFreightDetail> tblCustomerBaseFreightDetails3 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblQuoteRouteStop> tblQuoteRouteStops { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblQuoteRouteStop> tblQuoteRouteStops1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblQuoteRouteStop> tblQuoteRouteStops2 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblQuoteRouteStop> tblQuoteRouteStops3 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblTrailerRentalDetail> tblTrailerRentalDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblTrailerRentalDetail> tblTrailerRentalDetails1 { get; set; }

}

}
