//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LarastruckingApp.Repository.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccessorialFeesType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAccessorialFeesType()
        {
            this.tblFumigationAccessorialPrices = new HashSet<tblFumigationAccessorialPrice>();
            this.tblQuoteAccessorialPrices = new HashSet<tblQuoteAccessorialPrice>();
            this.tblShipmentAccessorialPrices = new HashSet<tblShipmentAccessorialPrice>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string PricingMethod { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFumigationAccessorialPrice> tblFumigationAccessorialPrices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblQuoteAccessorialPrice> tblQuoteAccessorialPrices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblShipmentAccessorialPrice> tblShipmentAccessorialPrices { get; set; }
    }
}
