//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LarastruckingApp.Repository.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccidentReportDocument
    {
        public int DocumentId { get; set; }
        public Nullable<int> AccidentReportId { get; set; }
        public Nullable<int> AccidentDocumentId { get; set; }
        public string ImageURL { get; set; }
        public string ImageName { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int ModifiedBy { get; set; }
        public bool IsDeleted { get; set; }
        public string DocumentName { get; set; }
    
        public virtual tblAccidentDocument tblAccidentDocument { get; set; }
        public virtual tblAccidentReport tblAccidentReport { get; set; }
    }
}
