
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LarastruckingApp.Repository.EF
{

using System;
    using System.Collections.Generic;
    
public partial class tblAccidentReport
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblAccidentReport()
    {

        this.tblAccidentReportDocuments = new HashSet<tblAccidentReportDocument>();

    }


    public int AccidentReportId { get; set; }

    public Nullable<int> EquipmentId { get; set; }

    public Nullable<int> DriverId { get; set; }

    public Nullable<System.DateTime> AccidentDate { get; set; }

    public string Address { get; set; }

    public string AccidentTime { get; set; }

    public string Comments { get; set; }

    public bool IsActive { get; set; }

    public System.DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public Nullable<System.DateTime> ModifiedDate { get; set; }

    public Nullable<int> ModifiedBy { get; set; }

    public bool IsDeleted { get; set; }

    public string PoliceReportNo { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblAccidentReportDocument> tblAccidentReportDocuments { get; set; }

    public virtual tblDriver tblDriver { get; set; }

    public virtual tblEquipmentDetail tblEquipmentDetail { get; set; }

}

}
