//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LarastruckingApp.Repository.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssessorialPrice
    {
        public int AssessorialPriceId { get; set; }
        public Nullable<int> QuoteId { get; set; }
        public Nullable<int> QuoteRouteStopsId { get; set; }
        public Nullable<int> RouteNo { get; set; }
        public Nullable<decimal> LoadingPerUnit { get; set; }
        public Nullable<decimal> LoadingAmount { get; set; }
        public Nullable<decimal> UnloadingPerUnit { get; set; }
        public Nullable<decimal> UnloadingAmount { get; set; }
        public Nullable<decimal> PalletExchangePerUnit { get; set; }
        public Nullable<decimal> PalletExchangeAmount { get; set; }
        public Nullable<decimal> DieselRefuelingAmount { get; set; }
        public Nullable<decimal> OvernightAmount { get; set; }
        public Nullable<decimal> SameDayAmount { get; set; }
        public Nullable<decimal> TotalAssessorialFee { get; set; }
    
        public virtual tblQuote tblQuote { get; set; }
        public virtual tblQuoteRouteStop tblQuoteRouteStop { get; set; }
        public virtual tblQuote tblQuote1 { get; set; }
        public virtual tblQuoteRouteStop tblQuoteRouteStop1 { get; set; }
    }
}
