
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LarastruckingApp.Repository.EF
{

using System;
    using System.Collections.Generic;
    
public partial class tblBaseFreightDetail
{

    public int BaseFreightDetailId { get; set; }

    public Nullable<int> PickupLocationId { get; set; }

    public Nullable<int> DeliveryLocationId { get; set; }

    public string Commodity { get; set; }

    public Nullable<int> FreightTypeId { get; set; }

    public Nullable<int> PricingMethodId { get; set; }

    public Nullable<decimal> MinFee { get; set; }

    public Nullable<decimal> Upto { get; set; }

    public Nullable<decimal> UnitPrice { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public System.DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public Nullable<System.DateTime> ModifiedDate { get; set; }

    public Nullable<int> ModifiedBy { get; set; }



    public virtual tblAddress tblAddress { get; set; }

    public virtual tblAddress tblAddress1 { get; set; }

    public virtual tblAddress tblAddress2 { get; set; }

    public virtual tblAddress tblAddress3 { get; set; }

    public virtual tblUser tblUser { get; set; }

    public virtual tblUser tblUser1 { get; set; }

    public virtual tblFreightType tblFreightType { get; set; }

    public virtual tblFreightType tblFreightType1 { get; set; }

    public virtual tblPricingMethod tblPricingMethod { get; set; }

    public virtual tblPricingMethod tblPricingMethod1 { get; set; }

}

}
