
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LarastruckingApp.Repository.EF
{

using System;
    using System.Collections.Generic;
    
public partial class tblCustomerContact
{

    public int ContactId { get; set; }

    public Nullable<long> CustomerId { get; set; }

    public string ContactFirstName { get; set; }

    public string ContactLastName { get; set; }

    public string ContactPhone { get; set; }

    public string ContactExtension { get; set; }

    public string ContactEmail { get; set; }

    public string ContactTitle { get; set; }



    public virtual tblCustomerRegistration tblCustomerRegistration { get; set; }

}

}
