//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LarastruckingApp.Repository.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomerBaseFreightDetail
    {
        public int CustomerBaseFreightDetailId { get; set; }
        public Nullable<int> QuoteId { get; set; }
        public Nullable<int> RouteNo { get; set; }
        public Nullable<int> QuoteRouteStopsId { get; set; }
        public Nullable<int> PickupLocationId { get; set; }
        public Nullable<int> DeliveryLocationId { get; set; }
        public string Commodity { get; set; }
        public Nullable<int> FreightTypeId { get; set; }
        public Nullable<int> PricingMethodId { get; set; }
        public Nullable<decimal> MinFee { get; set; }
        public Nullable<decimal> Upto { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public bool Hazardous { get; set; }
        public Nullable<decimal> Temperature { get; set; }
        public Nullable<decimal> QutWgtVlm { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<int> NoOfBox { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string Unit { get; set; }
        public Nullable<int> TrailerCount { get; set; }
    
        public virtual tblAddress tblAddress { get; set; }
        public virtual tblAddress tblAddress1 { get; set; }
        public virtual tblAddress tblAddress2 { get; set; }
        public virtual tblAddress tblAddress3 { get; set; }
        public virtual tblFreightType tblFreightType { get; set; }
        public virtual tblFreightType tblFreightType1 { get; set; }
        public virtual tblPricingMethod tblPricingMethod { get; set; }
        public virtual tblPricingMethod tblPricingMethod1 { get; set; }
        public virtual tblQuote tblQuote { get; set; }
        public virtual tblQuoteRouteStop tblQuoteRouteStop { get; set; }
        public virtual tblQuote tblQuote1 { get; set; }
        public virtual tblQuoteRouteStop tblQuoteRouteStop1 { get; set; }
    }
}
