//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LarastruckingApp.Repository.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomerRegistration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCustomerRegistration()
        {
            this.tblBaseAddresses = new HashSet<tblBaseAddress>();
            this.tblCustomerContacts = new HashSet<tblCustomerContact>();
            this.tblFumigations = new HashSet<tblFumigation>();
            this.tblQuotes = new HashSet<tblQuote>();
            this.tblQuotes1 = new HashSet<tblQuote>();
            this.tblTrailerRentals = new HashSet<tblTrailerRental>();
            this.tblWatingNotifications = new HashSet<tblWatingNotification>();
        }
    
        public long CustomerID { get; set; }
        public Nullable<int> UserId { get; set; }
        public string CustomerName { get; set; }
        public string Contact { get; set; }
        public string Website { get; set; }
        public string Comments { get; set; }
        public bool IsPickDropLocation { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public bool IsActive { get; set; }
        public bool IsFullFledgedCustomer { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public bool IsUploadShipment { get; set; }
        public bool IsWaitingTimeRequired { get; set; }
        public bool IsTemperatureRequired { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBaseAddress> tblBaseAddresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCustomerContact> tblCustomerContacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFumigation> tblFumigations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblQuote> tblQuotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblQuote> tblQuotes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTrailerRental> tblTrailerRentals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWatingNotification> tblWatingNotifications { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
