
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LarastruckingApp.Repository.EF
{

using System;
    using System.Collections.Generic;
    
public partial class tblDriver
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblDriver()
    {

        this.tblAccidentReports = new HashSet<tblAccidentReport>();

        this.tblDriverDocuments = new HashSet<tblDriverDocument>();

        this.tblShipmentEquipmentNdrivers = new HashSet<tblShipmentEquipmentNdriver>();

        this.tblTrailerRentalDetails = new HashSet<tblTrailerRentalDetail>();

        this.tblTrailerRentalDetails1 = new HashSet<tblTrailerRentalDetail>();

        this.tblWatingNotifications = new HashSet<tblWatingNotification>();

    }


    public int DriverID { get; set; }

    public Nullable<int> UserId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string CitizenShip { get; set; }

    public string EmailId { get; set; }

    public string Address1 { get; set; }

    public string Address2 { get; set; }

    public int Country { get; set; }

    public int State { get; set; }

    public string City { get; set; }

    public string Phone { get; set; }

    public string CellNumber { get; set; }

    public string BloodGroup { get; set; }

    public string Vehicle { get; set; }

    public string MedicalConditions { get; set; }

    public string EmergencyContactOne { get; set; }

    public string EmergencyPhoneNoOne { get; set; }

    public string RelationshipStatus1 { get; set; }

    public string EmergencyContactTwo { get; set; }

    public string EmergencyPhoneNoTwo { get; set; }

    public string RelationshipStatus2 { get; set; }

    public Nullable<System.DateTime> LeaveFrom { get; set; }

    public Nullable<System.DateTime> LeaveTo { get; set; }

    public bool IsActive { get; set; }

    public System.DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public Nullable<System.DateTime> ModifiedDate { get; set; }

    public Nullable<int> ModifiedBy { get; set; }

    public bool IsDeleted { get; set; }

    public string DOB { get; set; }

    public string ZipCode { get; set; }

    public string DriverLicence { get; set; }

    public string STANumber { get; set; }

    public Nullable<bool> FullTime { get; set; }

    public Nullable<int> LanguageId { get; set; }

    public string Extension { get; set; }

    public Nullable<System.DateTime> ExpirationDate { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblAccidentReport> tblAccidentReports { get; set; }

    public virtual tblCountry tblCountry { get; set; }

    public virtual tblCountry tblCountry1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblDriverDocument> tblDriverDocuments { get; set; }

    public virtual tblLanguage tblLanguage { get; set; }

    public virtual tblState tblState { get; set; }

    public virtual tblState tblState1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblShipmentEquipmentNdriver> tblShipmentEquipmentNdrivers { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblTrailerRentalDetail> tblTrailerRentalDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblTrailerRentalDetail> tblTrailerRentalDetails1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblWatingNotification> tblWatingNotifications { get; set; }

    public virtual tblUser tblUser { get; set; }

}

}
