
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LarastruckingApp.Repository.EF
{

using System;
    using System.Collections.Generic;
    
public partial class tblEquipmentFreight
{

    public int MapId { get; set; }

    public int EquipmentId { get; set; }

    public int FreightId { get; set; }



    public virtual tblEquipmentDetail tblEquipmentDetail { get; set; }

    public virtual tblFreightType tblFreightType { get; set; }

}

}
