//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LarastruckingApp.Repository.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEquipmentDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEquipmentDetail()
        {
            this.tblAccidentReports = new HashSet<tblAccidentReport>();
            this.tblShipmentEquipmentNdrivers = new HashSet<tblShipmentEquipmentNdriver>();
            this.tblEquipmentDoorTypes = new HashSet<tblEquipmentDoorType>();
            this.tblEquipmentFreights = new HashSet<tblEquipmentFreight>();
            this.tblPreTripCheckUps = new HashSet<tblPreTripCheckUp>();
        }
    
        public int EDID { get; set; }
        public Nullable<int> Decal { get; set; }
        public int VehicleType { get; set; }
        public string Model { get; set; }
        public string LicencePlate { get; set; }
        public string EquipmentNo { get; set; }
        public string WDimension { get; set; }
        public string HDimension { get; set; }
        public string LDimension { get; set; }
        public string Make { get; set; }
        public string VIN { get; set; }
        public string CubicFeet { get; set; }
        public string Ownedby { get; set; }
        public bool Active { get; set; }
        public string Comments { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public bool IsDeleted { get; set; }
        public string LeaseCompanyName { get; set; }
        public Nullable<System.DateTime> RegistrationExpiration { get; set; }
        public Nullable<int> Year { get; set; }
        public string Color { get; set; }
        public Nullable<System.DateTime> LeaseStartDate { get; set; }
        public Nullable<System.DateTime> LeaseEndDate { get; set; }
        public string RegistrationImageURL { get; set; }
        public string RegistrationImageName { get; set; }
        public string InsuranceImageURL { get; set; }
        public string InsauranceImageName { get; set; }
        public Nullable<bool> IsOutOfService { get; set; }
        public Nullable<System.DateTime> OutOfServiceStartDate { get; set; }
        public Nullable<System.DateTime> OutOfServiceEndDate { get; set; }
        public string MaxLoad { get; set; }
        public string RollerBed { get; set; }
        public string QRCodeNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAccidentReport> tblAccidentReports { get; set; }
        public virtual tblEquipmentType tblEquipmentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblShipmentEquipmentNdriver> tblShipmentEquipmentNdrivers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEquipmentDoorType> tblEquipmentDoorTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEquipmentFreight> tblEquipmentFreights { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPreTripCheckUp> tblPreTripCheckUps { get; set; }
    }
}
