
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LarastruckingApp.Repository.EF
{

using System;
    using System.Collections.Generic;
    
public partial class tblFumigation
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblFumigation()
    {

        this.tblDriverGpsTrakingHistories = new HashSet<tblDriverGpsTrakingHistory>();

        this.tblFumigationStatusHistories = new HashSet<tblFumigationStatusHistory>();

        this.tblFumigationEquipmentNDrivers = new HashSet<tblFumigationEquipmentNDriver>();

        this.tblFumigationAccessorialPrices = new HashSet<tblFumigationAccessorialPrice>();

    }


    public int FumigationId { get; set; }

    public Nullable<long> CustomerId { get; set; }

    public Nullable<int> StatusId { get; set; }

    public Nullable<int> SubStatusId { get; set; }

    public string Reason { get; set; }

    public string ShipmentRefNo { get; set; }

    public string VendorNconsignee { get; set; }

    public string RequestedBy { get; set; }

    public string Comments { get; set; }

    public bool IsActive { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public int CreatedBy { get; set; }

    public Nullable<System.DateTime> ModifiedOn { get; set; }

    public Nullable<int> ModifiedBy { get; set; }

    public bool IsDeleted { get; set; }

    public Nullable<System.DateTime> DeletedOn { get; set; }

    public Nullable<int> DeletedBy { get; set; }

    public Nullable<bool> WTReady { get; set; }

    public Nullable<bool> STReady { get; set; }



    public virtual tblCustomerRegistration tblCustomerRegistration { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblDriverGpsTrakingHistory> tblDriverGpsTrakingHistories { get; set; }

    public virtual tblUser tblUser { get; set; }

    public virtual tblUser tblUser1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblFumigationStatusHistory> tblFumigationStatusHistories { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblFumigationEquipmentNDriver> tblFumigationEquipmentNDrivers { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblFumigationAccessorialPrice> tblFumigationAccessorialPrices { get; set; }

    public virtual tblUser tblUser2 { get; set; }

    public virtual tblShipmentStatu tblShipmentStatu { get; set; }

    public virtual tblShipmentSubStatu tblShipmentSubStatu { get; set; }

}

}
