
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LarastruckingApp.Repository.EF
{

using System;
    using System.Collections.Generic;
    
public partial class tblFumigationEquipmentNDriver
{

    public int FumigationEquipmentNDriverId { get; set; }

    public Nullable<int> FumigationId { get; set; }

    public Nullable<int> FumigationRoutsId { get; set; }

    public Nullable<int> EquipmentId { get; set; }

    public Nullable<int> DriverId { get; set; }

    public Nullable<bool> IsPickUp { get; set; }

    public Nullable<bool> IsDeleted { get; set; }



    public virtual tblFumigation tblFumigation { get; set; }

    public virtual tblFumigationRout tblFumigationRout { get; set; }

}

}
