//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LarastruckingApp.Repository.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFumigationRout
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblFumigationRout()
        {
            this.tblDriverGpsTrakingHistories = new HashSet<tblDriverGpsTrakingHistory>();
            this.tblFumigationAccessorialPrices = new HashSet<tblFumigationAccessorialPrice>();
            this.tblFumigationDamagedImages = new HashSet<tblFumigationDamagedImage>();
            this.tblFumigationEquipmentNDrivers = new HashSet<tblFumigationEquipmentNDriver>();
            this.tblFumigationProofOfTemperatureImages = new HashSet<tblFumigationProofOfTemperatureImage>();
        }
    
        public int FumigationRoutsId { get; set; }
        public Nullable<int> RouteNo { get; set; }
        public Nullable<int> FumigationId { get; set; }
        public Nullable<int> FumigationTypeId { get; set; }
        public string AirWayBill { get; set; }
        public string CustomerPO { get; set; }
        public string ContainerNo { get; set; }
        public Nullable<int> PickUpLocation { get; set; }
        public Nullable<System.DateTime> PickUpArrival { get; set; }
        public Nullable<int> FumigationSite { get; set; }
        public Nullable<System.DateTime> FumigationArrival { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<System.DateTime> DepartureDate { get; set; }
        public Nullable<int> DeliveryLocation { get; set; }
        public Nullable<System.DateTime> DeliveryArrival { get; set; }
        public string Commodity { get; set; }
        public Nullable<decimal> PalletCount { get; set; }
        public Nullable<decimal> BoxCount { get; set; }
        public Nullable<int> BoxType { get; set; }
        public Nullable<decimal> Temperature { get; set; }
        public string TemperatureType { get; set; }
        public Nullable<decimal> TrailerDays { get; set; }
        public Nullable<int> PricingMethod { get; set; }
        public Nullable<decimal> MinFee { get; set; }
        public Nullable<decimal> AddFee { get; set; }
        public string TrailerPosition { get; set; }
        public Nullable<decimal> TotalFee { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DriverPickupArrival { get; set; }
        public Nullable<System.DateTime> DriverPickupDeparture { get; set; }
        public Nullable<System.DateTime> DriverDeliveryArrival { get; set; }
        public Nullable<System.DateTime> DriverDeliveryDeparture { get; set; }
        public string DigitalSignature { get; set; }
        public string ReceiverName { get; set; }
        public Nullable<decimal> UpTo { get; set; }
        public Nullable<System.DateTime> DriverFumigationIn { get; set; }
        public Nullable<System.DateTime> DriverLoadingStartTime { get; set; }
        public Nullable<System.DateTime> DriverLoadingFinishTime { get; set; }
        public Nullable<System.DateTime> DriverFumigationRelease { get; set; }
        public string DigitalSignaturePath { get; set; }
        public string VendorNConsignee { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDriverGpsTrakingHistory> tblDriverGpsTrakingHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFumigationAccessorialPrice> tblFumigationAccessorialPrices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFumigationDamagedImage> tblFumigationDamagedImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFumigationEquipmentNDriver> tblFumigationEquipmentNDrivers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFumigationProofOfTemperatureImage> tblFumigationProofOfTemperatureImages { get; set; }
    }
}
