//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LarastruckingApp.Repository.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLog
    {
        public int ID { get; set; }
        public string ErrorMessage { get; set; }
        public string Trace { get; set; }
        public string InnerException { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
