//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LarastruckingApp.Repository.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLeave
    {
        public int LeaveId { get; set; }
        public int DriverId { get; set; }
        public int UserId { get; set; }
        public System.DateTime TakenFrom { get; set; }
        public System.DateTime TakenTo { get; set; }
        public string Reason { get; set; }
        public int LeaveStatusId { get; set; }
        public int AppliedBy { get; set; }
        public System.DateTime AppliedOn { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
