
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LarastruckingApp.Repository.EF
{

using System;
    using System.Collections.Generic;
    
public partial class tblMailHistory
{

    public int MailHistoryId { get; set; }

    public string MailPurpose { get; set; }

    public string Status { get; set; }

    public string ToMail { get; set; }

    public string ToMailCC { get; set; }

    public string ToMailBCC { get; set; }

    public string MailSubject { get; set; }

    public string MailBody { get; set; }

    public byte[] FileByte { get; set; }

    public string ErrorMessage { get; set; }

    public string Trace { get; set; }

    public string InnerException { get; set; }

    public int CreatedBy { get; set; }

    public System.DateTime CreatedOn { get; set; }

}

}
