//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LarastruckingApp.Repository.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPreTripCheckUp
    {
        public int PreTripCheckupId { get; set; }
        public int ShipmentId { get; set; }
        public int EquipmentId { get; set; }
        public int UserId { get; set; }
        public Nullable<bool> IsTiresGood { get; set; }
        public Nullable<bool> IsBreaksGood { get; set; }
        public string Fuel { get; set; }
        public string LoadStraps { get; set; }
        public string OverAllCondition { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual tblEquipmentDetail tblEquipmentDetail { get; set; }
        public virtual tblShipment tblShipment { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
