
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LarastruckingApp.Repository.EF
{

using System;
    using System.Collections.Generic;
    
public partial class tblPackage
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblPackage()
    {

        this.tblTemperatures = new HashSet<tblTemperature>();

        this.tblTemperatures1 = new HashSet<tblTemperature>();

    }


    public long PackageID { get; set; }

    public Nullable<int> PackageType { get; set; }

    public Nullable<decimal> Quantity { get; set; }

    public Nullable<long> FreightType { get; set; }

    public Nullable<bool> IsHazardus { get; set; }

    public string PackageRefNo { get; set; }

    public Nullable<long> ShipmentID { get; set; }

    public Nullable<long> CreatedBy { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

    public Nullable<long> ModifiedBy { get; set; }

    public Nullable<System.DateTime> ModifiedOn { get; set; }

    public Nullable<bool> IsDeleted { get; set; }



    public virtual tblPackageType tblPackageType { get; set; }

    public virtual tblPackageType tblPackageType1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblTemperature> tblTemperatures { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblTemperature> tblTemperatures1 { get; set; }

}

}
