
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LarastruckingApp.Repository.EF
{

using System;
    using System.Collections.Generic;
    
public partial class tblPricingMethod
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblPricingMethod()
    {

        this.tblBaseFreightDetails = new HashSet<tblBaseFreightDetail>();

        this.tblBaseFreightDetails1 = new HashSet<tblBaseFreightDetail>();

        this.tblCustomerBaseFreightDetails = new HashSet<tblCustomerBaseFreightDetail>();

        this.tblCustomerBaseFreightDetails1 = new HashSet<tblCustomerBaseFreightDetail>();

        this.tblShipmentFreightDetails = new HashSet<tblShipmentFreightDetail>();

    }


    public int PricingMethodId { get; set; }

    public string PricingMethodName { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public string PricingMethodExt { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblBaseFreightDetail> tblBaseFreightDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblBaseFreightDetail> tblBaseFreightDetails1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblCustomerBaseFreightDetail> tblCustomerBaseFreightDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblCustomerBaseFreightDetail> tblCustomerBaseFreightDetails1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblShipmentFreightDetail> tblShipmentFreightDetails { get; set; }

}

}
