
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LarastruckingApp.Repository.EF
{

using System;
    using System.Collections.Generic;
    
public partial class tblQuote
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblQuote()
    {

        this.tblAssessorialPrices = new HashSet<tblAssessorialPrice>();

        this.tblAssessorialPrices1 = new HashSet<tblAssessorialPrice>();

        this.tblCustomerBaseFreightDetails = new HashSet<tblCustomerBaseFreightDetail>();

        this.tblCustomerBaseFreightDetails1 = new HashSet<tblCustomerBaseFreightDetail>();

        this.tblQuoteAccessorialPrices = new HashSet<tblQuoteAccessorialPrice>();

        this.tblQuoteRouteStops = new HashSet<tblQuoteRouteStop>();

        this.tblQuoteRouteStops1 = new HashSet<tblQuoteRouteStop>();

    }


    public int QuoteId { get; set; }

    public Nullable<long> CustomerId { get; set; }

    public string QuotesName { get; set; }

    public System.DateTime QuoteDate { get; set; }

    public System.DateTime ValidUptoDate { get; set; }

    public Nullable<decimal> FinalTotalAmount { get; set; }

    public Nullable<int> QuoteStatusId { get; set; }

    public bool IsDeleted { get; set; }

    public System.DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public Nullable<System.DateTime> ModifiedDate { get; set; }

    public Nullable<int> ModifiedBy { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblAssessorialPrice> tblAssessorialPrices { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblAssessorialPrice> tblAssessorialPrices1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblCustomerBaseFreightDetail> tblCustomerBaseFreightDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblCustomerBaseFreightDetail> tblCustomerBaseFreightDetails1 { get; set; }

    public virtual tblCustomerRegistration tblCustomerRegistration { get; set; }

    public virtual tblCustomerRegistration tblCustomerRegistration1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblQuoteAccessorialPrice> tblQuoteAccessorialPrices { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblQuoteRouteStop> tblQuoteRouteStops { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblQuoteRouteStop> tblQuoteRouteStops1 { get; set; }

    public virtual tblUser tblUser { get; set; }

    public virtual tblUser tblUser1 { get; set; }

}

}
