
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LarastruckingApp.Repository.EF
{

using System;
    using System.Collections.Generic;
    
public partial class tblShipmentRoutesStop
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblShipmentRoutesStop()
    {

        this.tblDamagedImages = new HashSet<tblDamagedImage>();

        this.tblDriverGpsTrakingHistories = new HashSet<tblDriverGpsTrakingHistory>();

        this.tblProofOfTemperatureImages = new HashSet<tblProofOfTemperatureImage>();

        this.tblShipmentAccessorialPrices = new HashSet<tblShipmentAccessorialPrice>();

        this.tblShipmentFreightDetails = new HashSet<tblShipmentFreightDetail>();

        this.tblWatingNotifications = new HashSet<tblWatingNotification>();

        this.tblWatingNotifications1 = new HashSet<tblWatingNotification>();

    }


    public int ShippingRoutesId { get; set; }

    public Nullable<int> ShippingId { get; set; }

    public Nullable<int> RouteNo { get; set; }

    public Nullable<int> PickupLocationId { get; set; }

    public Nullable<int> DeliveryLocationId { get; set; }

    public Nullable<System.DateTime> PickDateTime { get; set; }

    public Nullable<System.DateTime> DeliveryDateTime { get; set; }

    public Nullable<System.DateTime> PickUpDateTimeTo { get; set; }

    public Nullable<System.DateTime> DeliveryDateTimeTo { get; set; }

    public string Comment { get; set; }

    public Nullable<System.DateTime> DriverPickupArrival { get; set; }

    public Nullable<System.DateTime> DriverPickupDeparture { get; set; }

    public Nullable<System.DateTime> DriverDeliveryArrival { get; set; }

    public Nullable<System.DateTime> DriverDeliveryDeparture { get; set; }

    public bool IsDeleted { get; set; }

    public Nullable<System.DateTime> DeletedOn { get; set; }

    public Nullable<int> DeletedBy { get; set; }

    public string DigitalSignature { get; set; }

    public string ReceiverName { get; set; }

    public bool IsAppointmentRequired { get; set; }

    public bool IsPickUpWaitingTimeRequired { get; set; }

    public bool IsDeliveryWaitingTimeRequired { get; set; }

    public string DigitalSignaturePath { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblDamagedImage> tblDamagedImages { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblDriverGpsTrakingHistory> tblDriverGpsTrakingHistories { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblProofOfTemperatureImage> tblProofOfTemperatureImages { get; set; }

    public virtual tblShipment tblShipment { get; set; }

    public virtual tblShipment tblShipment1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblShipmentAccessorialPrice> tblShipmentAccessorialPrices { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblShipmentFreightDetail> tblShipmentFreightDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblWatingNotification> tblWatingNotifications { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblWatingNotification> tblWatingNotifications1 { get; set; }

}

}
