//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LarastruckingApp.Repository.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblShipmentStatus1
    {
        public int StatusId { get; set; }
        public string StatusName { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public string Colour { get; set; }
        public string ImageURL { get; set; }
        public Nullable<int> FumigationDisplayOrder { get; set; }
        public Nullable<bool> IsFumigation { get; set; }
        public Nullable<bool> IsShipment { get; set; }
        public string StatusAbbreviation { get; set; }
        public string FontColor { get; set; }
        public Nullable<int> DisplayOrderCustomer { get; set; }
        public Nullable<int> FumigationDisplayOrderCustomer { get; set; }
        public string GrayImageURL { get; set; }
    }
}
