//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LarastruckingApp.Repository.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblShipmentEquipmentNdriver
    {
        public int ShipmentEquipmentNdriverId { get; set; }
        public Nullable<int> ShipmentId { get; set; }
        public Nullable<int> DriverId { get; set; }
        public Nullable<int> EquipmentId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual tblDriver tblDriver { get; set; }
        public virtual tblEquipmentDetail tblEquipmentDetail { get; set; }
        public virtual tblShipment tblShipment { get; set; }
    }
}
