
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LarastruckingApp.Repository.EF
{

using System;
    using System.Collections.Generic;
    
public partial class tblShipment
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblShipment()
    {

        this.tblDriverGpsTrakingHistories = new HashSet<tblDriverGpsTrakingHistory>();

        this.tblPreTripCheckUps = new HashSet<tblPreTripCheckUp>();

        this.tblShipmentStatusHistories = new HashSet<tblShipmentStatusHistory>();

        this.tblShipmentCommments = new HashSet<tblShipmentCommment>();

        this.tblShipmentEquipmentNdrivers = new HashSet<tblShipmentEquipmentNdriver>();

        this.tblShipmentAccessorialPrices = new HashSet<tblShipmentAccessorialPrice>();

        this.tblShipmentFreightDetails = new HashSet<tblShipmentFreightDetail>();

        this.tblShipmentRoutesStops = new HashSet<tblShipmentRoutesStop>();

        this.tblShipmentRoutesStops1 = new HashSet<tblShipmentRoutesStop>();

        this.tblWatingNotifications = new HashSet<tblWatingNotification>();

    }


    public int ShipmentId { get; set; }

    public Nullable<int> QuoteId { get; set; }

    public Nullable<int> StatusId { get; set; }

    public Nullable<int> SubStatusId { get; set; }

    public Nullable<long> CustomerId { get; set; }

    public string RequestedBy { get; set; }

    public string Reason { get; set; }

    public string ShipmentRefNo { get; set; }

    public string AirWayBill { get; set; }

    public string CustomerPO { get; set; }

    public string OrderNo { get; set; }

    public string CustomerRef { get; set; }

    public string ContainerNo { get; set; }

    public string PurchaseDoc { get; set; }

    public int EquipmentId { get; set; }

    public int DriverId { get; set; }

    public Nullable<decimal> FinalTotalAmount { get; set; }

    public string DriverInstruction { get; set; }

    public bool IsDeleted { get; set; }

    public System.DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public Nullable<System.DateTime> ModifiedDate { get; set; }

    public Nullable<int> ModifiedBy { get; set; }

    public Nullable<System.DateTime> DeletedOn { get; set; }

    public Nullable<int> DeletedBy { get; set; }

    public string VendorNconsignee { get; set; }

    public string UploadedFileName { get; set; }

    public Nullable<bool> IsWaiting { get; set; }

    public bool IsReady { get; set; }

    public Nullable<bool> WTReady { get; set; }

    public Nullable<bool> STReady { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblDriverGpsTrakingHistory> tblDriverGpsTrakingHistories { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblPreTripCheckUp> tblPreTripCheckUps { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblShipmentStatusHistory> tblShipmentStatusHistories { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblShipmentCommment> tblShipmentCommments { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblShipmentEquipmentNdriver> tblShipmentEquipmentNdrivers { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblShipmentAccessorialPrice> tblShipmentAccessorialPrices { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblShipmentFreightDetail> tblShipmentFreightDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblShipmentRoutesStop> tblShipmentRoutesStops { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblShipmentRoutesStop> tblShipmentRoutesStops1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblWatingNotification> tblWatingNotifications { get; set; }

}

}
