//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LarastruckingApp.Repository.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblShipmentFreightDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblShipmentFreightDetail()
        {
            this.tblProofOfTemperatureImages = new HashSet<tblProofOfTemperatureImage>();
        }
    
        public int ShipmentBaseFreightDetailId { get; set; }
        public Nullable<int> ShipmentId { get; set; }
        public Nullable<int> ShipmentRouteStopeId { get; set; }
        public string Commodity { get; set; }
        public Nullable<int> FreightTypeId { get; set; }
        public Nullable<int> PricingMethodId { get; set; }
        public Nullable<decimal> MinFee { get; set; }
        public Nullable<decimal> UpTo { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public bool Hazardous { get; set; }
        public Nullable<decimal> Temperature { get; set; }
        public string TemperatureType { get; set; }
        public Nullable<decimal> QuantityNweight { get; set; }
        public Nullable<int> PcsType { get; set; }
        public Nullable<int> NoOfBox { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public string Comments { get; set; }
        public Nullable<int> TrailerCount { get; set; }
        public Nullable<int> PartialBox { get; set; }
        public Nullable<int> PartialPallete { get; set; }
        public bool IsPartialShipment { get; set; }
    
        public virtual tblFreightType tblFreightType { get; set; }
        public virtual tblPricingMethod tblPricingMethod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProofOfTemperatureImage> tblProofOfTemperatureImages { get; set; }
        public virtual tblShipment tblShipment { get; set; }
        public virtual tblShipmentRoutesStop tblShipmentRoutesStop { get; set; }
    }
}
