
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LarastruckingApp.Repository.EF
{

using System;
    using System.Collections.Generic;
    
public partial class tblShipmentSubStatu
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblShipmentSubStatu()
    {

        this.tblFumigations = new HashSet<tblFumigation>();

        this.tblFumigationStatusHistories = new HashSet<tblFumigationStatusHistory>();

        this.tblShipmentStatusHistories = new HashSet<tblShipmentStatusHistory>();

    }


    public int SubStatusId { get; set; }

    public int StatusId { get; set; }

    public string SubStatusName { get; set; }

    public int DisplayOrder { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public string SpanishSubStatusName { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblFumigation> tblFumigations { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblFumigationStatusHistory> tblFumigationStatusHistories { get; set; }

    public virtual tblShipmentStatu tblShipmentStatu { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblShipmentStatusHistory> tblShipmentStatusHistories { get; set; }

}

}
