
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LarastruckingApp.Repository.EF
{

using System;
    using System.Collections.Generic;
    
public partial class tblTimeCardLoan
{

    public int Id { get; set; }

    public int UserId { get; set; }

    public Nullable<decimal> Loan { get; set; }

    public Nullable<bool> IsPaid { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public int CreatedBy { get; set; }

}

}
