//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LarastruckingApp.Repository.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTemperature
    {
        public long TemperatureID { get; set; }
        public Nullable<long> ShipmentID { get; set; }
        public Nullable<long> DeliveryID { get; set; }
        public string Temperature { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> PackageID { get; set; }
    
        public virtual tblDelivery tblDelivery { get; set; }
        public virtual tblDelivery tblDelivery1 { get; set; }
        public virtual tblPackage tblPackage { get; set; }
        public virtual tblPackage tblPackage1 { get; set; }
    }
}
