
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LarastruckingApp.Repository.EF
{

using System;
    using System.Collections.Generic;
    
public partial class tblTrailerRental
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblTrailerRental()
    {

        this.tblTrailerRentalDetails = new HashSet<tblTrailerRentalDetail>();

    }


    public int TrailerRentalId { get; set; }

    public Nullable<long> CustomerId { get; set; }

    public string TrailerInstruction { get; set; }

    public Nullable<decimal> GrandTotal { get; set; }

    public System.DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public Nullable<System.DateTime> ModifiedDate { get; set; }

    public Nullable<int> ModifiedBy { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<int> DeletedBy { get; set; }

    public Nullable<System.DateTime> DeletedDate { get; set; }



    public virtual tblCustomerRegistration tblCustomerRegistration { get; set; }

    public virtual tblUser tblUser { get; set; }

    public virtual tblUser tblUser1 { get; set; }

    public virtual tblUser tblUser2 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblTrailerRentalDetail> tblTrailerRentalDetails { get; set; }

}

}
