
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LarastruckingApp.Repository.EF
{

using System;
    using System.Collections.Generic;
    
public partial class tblTransportVehical
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblTransportVehical()
    {

        this.tblDeliveries = new HashSet<tblDelivery>();

    }


    public long TransportVehicalID { get; set; }

    public Nullable<int> VehicleType { get; set; }

    public Nullable<int> VehicleStatus { get; set; }

    public bool PreTripCheckup_Tires { get; set; }

    public bool PreTripCheckup_Breaks { get; set; }

    public bool PreTripCheckup_fuel { get; set; }

    public Nullable<System.DateTime> CheckupDate { get; set; }

    public Nullable<long> CheckupBy { get; set; }

    public Nullable<long> CreatedBy { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

    public Nullable<long> ModifiedBy { get; set; }

    public Nullable<System.DateTime> ModifiedOn { get; set; }

    public Nullable<bool> IsDeleted { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblDelivery> tblDeliveries { get; set; }

    public virtual tblEquipmentStatu tblEquipmentStatu { get; set; }

}

}
