
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LarastruckingApp.Repository.EF
{

using System;
    using System.Collections.Generic;
    
public partial class tblUser
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblUser()
    {

        this.tblBaseFreightDetails = new HashSet<tblBaseFreightDetail>();

        this.tblBaseFreightDetails1 = new HashSet<tblBaseFreightDetail>();

        this.tblCustomerRegistrations = new HashSet<tblCustomerRegistration>();

        this.tblDamagedImages = new HashSet<tblDamagedImage>();

        this.tblDrivers = new HashSet<tblDriver>();

        this.tblDriverGpsTrakingHistories = new HashSet<tblDriverGpsTrakingHistory>();

        this.tblFumigations = new HashSet<tblFumigation>();

        this.tblFumigations1 = new HashSet<tblFumigation>();

        this.tblFumigations2 = new HashSet<tblFumigation>();

        this.tblFumigationStatusHistories = new HashSet<tblFumigationStatusHistory>();

        this.tblLeaves = new HashSet<tblLeave>();

        this.tblPreTripCheckUps = new HashSet<tblPreTripCheckUp>();

        this.tblProofOfTemperatureImages = new HashSet<tblProofOfTemperatureImage>();

        this.tblQuotes = new HashSet<tblQuote>();

        this.tblQuotes1 = new HashSet<tblQuote>();

        this.tblShipmentStatusHistories = new HashSet<tblShipmentStatusHistory>();

        this.tblTrailerRentals = new HashSet<tblTrailerRental>();

        this.tblTrailerRentals1 = new HashSet<tblTrailerRental>();

        this.tblTrailerRentals2 = new HashSet<tblTrailerRental>();

        this.tblTrailerRentalDetails = new HashSet<tblTrailerRentalDetail>();

        this.tblTrailerRentalDetails1 = new HashSet<tblTrailerRentalDetail>();

        this.tblTrailerRentalDetails2 = new HashSet<tblTrailerRentalDetail>();

        this.tblUserRoles = new HashSet<tblUserRole>();

    }


    public int Userid { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public int CreatedBy { get; set; }

    public Nullable<System.DateTime> ModifiedOn { get; set; }

    public Nullable<int> ModifiedBy { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public string GUID { get; set; }

    public Nullable<System.DateTime> ResetPasswordDateTime { get; set; }

    public Nullable<System.DateTime> GuidGenratedDateTime { get; set; }

    public string UserType { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblBaseFreightDetail> tblBaseFreightDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblBaseFreightDetail> tblBaseFreightDetails1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblCustomerRegistration> tblCustomerRegistrations { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblDamagedImage> tblDamagedImages { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblDriver> tblDrivers { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblDriverGpsTrakingHistory> tblDriverGpsTrakingHistories { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblFumigation> tblFumigations { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblFumigation> tblFumigations1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblFumigation> tblFumigations2 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblFumigationStatusHistory> tblFumigationStatusHistories { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblLeave> tblLeaves { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblPreTripCheckUp> tblPreTripCheckUps { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblProofOfTemperatureImage> tblProofOfTemperatureImages { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblQuote> tblQuotes { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblQuote> tblQuotes1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblShipmentStatusHistory> tblShipmentStatusHistories { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblTrailerRental> tblTrailerRentals { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblTrailerRental> tblTrailerRentals1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblTrailerRental> tblTrailerRentals2 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblTrailerRentalDetail> tblTrailerRentalDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblTrailerRentalDetail> tblTrailerRentalDetails1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblTrailerRentalDetail> tblTrailerRentalDetails2 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblUserRole> tblUserRoles { get; set; }

}

}
