//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LarastruckingApp.Repository.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUploadShipmentSample
    {
        public int SampleId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string ShipmentSamplePath { get; set; }
    }
}
