//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LarastruckingApp.Repository.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWatingNotification
    {
        public int WatingNotificationId { get; set; }
        public Nullable<int> ShipmentId { get; set; }
        public Nullable<int> ShipmentRouteId { get; set; }
        public Nullable<System.DateTime> PickupArrivedOn { get; set; }
        public Nullable<System.DateTime> PickupDepartedOn { get; set; }
        public Nullable<System.DateTime> DeliveryArrivedOn { get; set; }
        public Nullable<System.DateTime> DeliveryDepartedOn { get; set; }
        public Nullable<int> PickUpLocationId { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public string EquipmentNo { get; set; }
        public Nullable<int> DriverId { get; set; }
        public bool IsDelivered { get; set; }
        public bool IsEmailSentPWS { get; set; }
        public bool IsEmailSentPWE { get; set; }
        public bool IsEmailSentDWS { get; set; }
        public bool IsEmailSentDWE { get; set; }
        public Nullable<int> DeliveryLocationId { get; set; }
        public string TotalPickupWaitingTime { get; set; }
        public string TotalDeliveryWaitingTime { get; set; }
    
        public virtual tblCustomerRegistration tblCustomerRegistration { get; set; }
        public virtual tblDriver tblDriver { get; set; }
        public virtual tblShipment tblShipment { get; set; }
        public virtual tblShipmentRoutesStop tblShipmentRoutesStop { get; set; }
        public virtual tblShipmentRoutesStop tblShipmentRoutesStop1 { get; set; }
    }
}
