
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LarastruckingApp.Repository.EF
{

using System;
    using System.Collections.Generic;
    
public partial class view_GetOrderTakenShipment_Text
{

    public Nullable<int> totalcountrow { get; set; }

    public int shipmentid { get; set; }

    public string airwaybill { get; set; }

    public string customerpo { get; set; }

    public int statusid { get; set; }

    public string statusname { get; set; }

    public Nullable<long> customerid { get; set; }

    public string customername { get; set; }

    public string driver { get; set; }

    public string equipment { get; set; }

    public string pickupdate { get; set; }

    public string deliverydate { get; set; }

    public string pickuplocation { get; set; }

    public string deliverylocation { get; set; }

    public string quantity { get; set; }

}

}
