
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LarastruckingApp.Repository.EF
{

using System;
    using System.Collections.Generic;
    
public partial class view_GetOrderNotTakenShipment
{

    public Nullable<int> TotalCountRow { get; set; }

    public int ShipmentId { get; set; }

    public string AirWayBill { get; set; }

    public string CustomerPO { get; set; }

    public string OrderNo { get; set; }

    public string CustomerRef { get; set; }

    public string ContainerNo { get; set; }

    public string PurchaseDoc { get; set; }

    public Nullable<int> StatusId { get; set; }

    public Nullable<bool> WTReady { get; set; }

    public Nullable<bool> STReady { get; set; }

    public string StatusName { get; set; }

    public Nullable<long> CustomerID { get; set; }

    public string CustomerName { get; set; }

    public string Driver { get; set; }

    public string Equipment { get; set; }

    public string PickupDate { get; set; }

    public string DeliveryDate { get; set; }

    public string PickupLocation { get; set; }

    public string DeliveryLocation { get; set; }

    public string Quantity { get; set; }

    public string Comments { get; set; }

    public int ApproveStatus { get; set; }

    public string Temperature { get; set; }

    public string Commodity { get; set; }

}

}
