//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LarastruckingApp.Repository.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_DriverDashboard
    {
        public int ShipmentId { get; set; }
        public Nullable<int> DriverId { get; set; }
        public int PreTripCheckupId { get; set; }
        public Nullable<System.DateTime> PickDateTime { get; set; }
        public string DriverEquipment { get; set; }
        public string ShipmentRefNo { get; set; }
        public string QuantityNMethod { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string StatusName { get; set; }
        public string PreTripStatus { get; set; }
    }
}
