
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LarastruckingApp.Repository.EF
{

using System;
    using System.Collections.Generic;
    
public partial class view_GetOtherFumigation
{

    public int FumigationId { get; set; }

    public string VendorNConsignee { get; set; }

    public string CustomerName { get; set; }

    public string StatusName { get; set; }

    public string FumigationTypes { get; set; }

    public string TrailerPosition { get; set; }

    public string PickupLocation { get; set; }

    public string FumigationSite { get; set; }

    public string DeliveryLocation { get; set; }

    public string ActLoadingStart { get; set; }

    public string ActLoadingFinish { get; set; }

    public string ActFumigationIn { get; set; }

    public string ActFumigationRelease { get; set; }

    public string ActDepartureDate { get; set; }

    public string ActDeliveryArrival { get; set; }

    public string ActDeliveryDeparture { get; set; }

    public string Comments { get; set; }

    public string Temperature { get; set; }

    public string AWB { get; set; }

    public string CustomerPO { get; set; }

    public string ContainerNo { get; set; }

    public Nullable<bool> WTReady { get; set; }

    public Nullable<bool> STReady { get; set; }

    public string BoxCount { get; set; }

    public string PalletCount { get; set; }

    public string PickUpDriver { get; set; }

    public string PickUpEquipment { get; set; }

    public string DeliveryDriver { get; set; }

    public string DeliveryEquipment { get; set; }

    public string RequestedAt { get; set; }

    public int ApproveStatus { get; set; }

    public Nullable<int> TotalCount { get; set; }

}

}
