
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LarastruckingApp.Repository.EF
{

using System;
    using System.Collections.Generic;
    
public partial class View_DriverShipmentDetail
{

    public int Id { get; set; }

    public string QuantityNMethod { get; set; }

    public string AirWayBill { get; set; }

    public string CustomerPO { get; set; }

    public string OrderNo { get; set; }

    public string DriverInstruction { get; set; }

    public string PickupLocation { get; set; }

    public string DeliveryLocation { get; set; }

    public string StatusName { get; set; }

    public string FontColor { get; set; }

    public string Colour { get; set; }

    public string DriverEquipment { get; set; }

    public string PreTripStatus { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public string Types { get; set; }

    public Nullable<int> UserId { get; set; }

}

}
