
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LarastruckingApp.Repository.EF
{

using System;
    using System.Collections.Generic;
    
public partial class view_tblShipmentFreightDetail
{

    public int ShipmentBaseFreightDetailId { get; set; }

    public bool IsDeleted { get; set; }

    public bool IsPartialShipment { get; set; }

    public Nullable<int> ShipmentId { get; set; }

    public Nullable<int> ShipmentRouteStopeId { get; set; }

    public Nullable<decimal> QuantityNweight { get; set; }

    public Nullable<int> NoOfBox { get; set; }

    public Nullable<decimal> Weight { get; set; }

    public string Unit { get; set; }

    public Nullable<int> PartialPallete { get; set; }

    public Nullable<int> PartialBox { get; set; }

}

}
