//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LarastruckingApp.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LarastruckingResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LarastruckingResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LarastruckingApp.Resource.LarastruckingResource", typeof(LarastruckingResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to already exist!.
        /// </summary>
        public static string AlreadyExist {
            get {
                return ResourceManager.GetString("AlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment successfully approved..
        /// </summary>
        public static string ApproveShipment {
            get {
                return ResourceManager.GetString("ApproveShipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New password link.
        /// </summary>
        public static string CreateNewPasswordLink {
            get {
                return ResourceManager.GetString("CreateNewPasswordLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new password link send on your registered Email address..
        /// </summary>
        public static string CreateNewPasswordLinkSendOnYourRegisteredEmailaddress {
            get {
                return ResourceManager.GetString("CreateNewPasswordLinkSendOnYourRegisteredEmailaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer already exists!.
        /// </summary>
        public static string CustomerExists {
            get {
                return ResourceManager.GetString("CustomerExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success! Your data has been deleted!.
        /// </summary>
        public static string DataDeleteSuccessfully {
            get {
                return ResourceManager.GetString("DataDeleteSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success! Your data has been saved!.
        /// </summary>
        public static string DataSaveSuccessfully {
            get {
                return ResourceManager.GetString("DataSaveSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success! Your data has been updated!.
        /// </summary>
        public static string DataUpdateSuccessfully {
            get {
                return ResourceManager.GetString("DataUpdateSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LARAS DRIVER DOCUMENT EXPIRATION ADVICE |.
        /// </summary>
        public static string DriverDocumetExpiration {
            get {
                return ResourceManager.GetString("DriverDocumetExpiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Email .
        /// </summary>
        public static string EmailAddressRequired {
            get {
                return ResourceManager.GetString("EmailAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Valid Email .
        /// </summary>
        public static string EmailValidation {
            get {
                return ResourceManager.GetString("EmailValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a registered email..
        /// </summary>
        public static string EnterRegisteredUserName {
            get {
                return ResourceManager.GetString("EnterRegisteredUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occured.
        /// </summary>
        public static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please correct you excel file format..
        /// </summary>
        public static string ExcelFileFormate {
            get {
                return ResourceManager.GetString("ExcelFileFormate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exists.
        /// </summary>
        public static string Exists {
            get {
                return ResourceManager.GetString("Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter First Name..
        /// </summary>
        public static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForgotPassword/ResetPassword/.
        /// </summary>
        public static string ForgotPasswordResetPassword {
            get {
                return ResourceManager.GetString("ForgotPasswordResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input!.
        /// </summary>
        public static string InvalidInputs {
            get {
                return ResourceManager.GetString("InvalidInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User name and Password. .
        /// </summary>
        public static string InvalidUserNamePassword {
            get {
                return ResourceManager.GetString("InvalidUserNamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LARA&apos;S FUMIGATION ADVICE |  @AWB/PO/ORD | @TRLR | @STATUS.
        /// </summary>
        public static string LarasFumigationAdvice {
            get {
                return ResourceManager.GetString("LarasFumigationAdvice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LARA&apos;S QUOTE ENCLOSED  | $CUSTOMERNAME | $QUOTENAME.
        /// </summary>
        public static string LarasQuoteAdvice {
            get {
                return ResourceManager.GetString("LarasQuoteAdvice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Last Name.
        /// </summary>
        public static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed.
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter correct details!.
        /// </summary>
        public static string LoginIncorrectDetails {
            get {
                return ResourceManager.GetString("LoginIncorrectDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Successfully..
        /// </summary>
        public static string LoginSuccessfully {
            get {
                return ResourceManager.GetString("LoginSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Accident  Save Sucessfully!.
        /// </summary>
        public static string msgAddAccidentReport {
            get {
                return ResourceManager.GetString("msgAddAccidentReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Successfully Added..
        /// </summary>
        public static string msgAddCustomer {
            get {
                return ResourceManager.GetString("msgAddCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Successfully Added..
        /// </summary>
        public static string msgAddDriver {
            get {
                return ResourceManager.GetString("msgAddDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Successfully Deleted..
        /// </summary>
        public static string msgDeleteCustomer {
            get {
                return ResourceManager.GetString("msgDeleteCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Successfully Deleted..
        /// </summary>
        public static string msgDeleteDriver {
            get {
                return ResourceManager.GetString("msgDeleteDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Update Successfully..
        /// </summary>
        public static string msgPermissionUpdateSuccessfully {
            get {
                return ResourceManager.GetString("msgPermissionUpdateSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Accident Successfully Updated..
        /// </summary>
        public static string msgUpdateAccidentReport {
            get {
                return ResourceManager.GetString("msgUpdateAccidentReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Successfully Updated..
        /// </summary>
        public static string msgUpdateCustomer {
            get {
                return ResourceManager.GetString("msgUpdateCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Successfully  Updated..
        /// </summary>
        public static string msgUpdateDriver {
            get {
                return ResourceManager.GetString("msgUpdateDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Accident Successfully Deleted..
        /// </summary>
        public static string mstDeleteAccidentReport {
            get {
                return ResourceManager.GetString("mstDeleteAccidentReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Password..
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password successfully changed.
        /// </summary>
        public static string PasswordSuccessfullyChanged {
            get {
                return ResourceManager.GetString("PasswordSuccessfullyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter registered UserName..
        /// </summary>
        public static string PleaseEnterRegisteredUserName {
            get {
                return ResourceManager.GetString("PleaseEnterRegisteredUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proof of temperature.
        /// </summary>
        public static string ProofOfTemperature {
            get {
                return ResourceManager.GetString("ProofOfTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote.pdf.
        /// </summary>
        public static string QuoteFileName {
            get {
                return ResourceManager.GetString("QuoteFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br /&gt;&lt;br /&gt;As per request, we have sent the quote. Please find attachment quote for.
        /// </summary>
        public static string QuoteMailBody {
            get {
                return ResourceManager.GetString("QuoteMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br /&gt;&lt;br /&gt;  Best Regards,&lt;br/&gt; Lara’s Trucking &amp; Logistics.
        /// </summary>
        public static string QuoteMailSignature {
            get {
                return ResourceManager.GetString("QuoteMailSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote Detail.
        /// </summary>
        public static string QuoteMailSubject {
            get {
                return ResourceManager.GetString("QuoteMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote successfully sent..
        /// </summary>
        public static string QuoteSuccessMessage {
            get {
                return ResourceManager.GetString("QuoteSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password link send on your registered Email address..
        /// </summary>
        public static string ResetPasswordLinkSendOnYourRegisteredEmailaddress {
            get {
                return ResourceManager.GetString("ResetPasswordLinkSendOnYourRegisteredEmailaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string RoleCustomerId {
            get {
                return ResourceManager.GetString("RoleCustomerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string RoleDriver {
            get {
                return ResourceManager.GetString("RoleDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Role..
        /// </summary>
        public static string RoleRequired {
            get {
                return ResourceManager.GetString("RoleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string s {
            get {
                return ResourceManager.GetString("s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LARA&apos;S SHIPMENT ADVICE | @AWB | @STATUS.
        /// </summary>
        public static string ShipmentStatusChanges {
            get {
                return ResourceManager.GetString("ShipmentStatusChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong!.
        /// </summary>
        public static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/Status/Gray/dots.png.
        /// </summary>
        public static string StatusDotsGrayImage {
            get {
                return ResourceManager.GetString("StatusDotsGrayImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/Status/dots.png.
        /// </summary>
        public static string StatusDotsImage {
            get {
                return ResourceManager.GetString("StatusDotsImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username already exists!.
        /// </summary>
        public static string UserAlreadyExist {
            get {
                return ResourceManager.GetString("UserAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter UserName ..
        /// </summary>
        public static string UsernameRequired {
            get {
                return ResourceManager.GetString("UsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string UserRole_Customer {
            get {
                return ResourceManager.GetString("UserRole_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver.
        /// </summary>
        public static string UserRole_Driver {
            get {
                return ResourceManager.GetString("UserRole_Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User created successfully. Please check your email for further instruction..
        /// </summary>
        public static string UserSuccess {
            get {
                return ResourceManager.GetString("UserSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LARAS WAITING TIME START ADVICE  | @AWB | @STATUS.
        /// </summary>
        public static string WaitingTimeStatus {
            get {
                return ResourceManager.GetString("WaitingTimeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LARA&apos;S TOTAL WAITING TIME ACCRUED ADVICE  | @AWB | @STATUS.
        /// </summary>
        public static string WaitingTimeTotal {
            get {
                return ResourceManager.GetString("WaitingTimeTotal", resourceCulture);
            }
        }
    }
}
